[TextView]
bullet_icon_size=GTK_ICON_SIZE_MENU
indent=30
tabs=None
linespacing=3
wrapped-lines-linespacing=0
#font=! style=71083284 variant=800544037 17
font=Ubuntu 17
justify=LEFT
pixels-inside-wrap=30
#name=atom-one-light
#version=1.0

[Tag strong]
foreground=#4078f2
weight=PANGO_WEIGHT_BOLD

[Tag emphasis]
foreground=#e45649
style=PANGO_STYLE_ITALIC

[Tag mark]
foreground=#f2ae49
background=#f5f5f5

[Tag strike]
foreground=#a0a1a7
strikethrough=false

[Tag indent]
foreground=#9caeeb

[Tag code]
foreground=#986801
family=monospace

[Tag pre]
foreground=#986801
family=monospace
indent=20

[Tag page-link]
foreground=#50a14f
underline=PANGO_UNDERLINE_SINGLE

[Tag link]
foreground=#a626a4
underline=PANGO_UNDERLINE_SINGLE

[Tag tag]
foreground=#d19a66

[Tag h1]
foreground=#0184bc
underline=PANGO_UNDERLINE_SINGLE
weight=PANGO_WEIGHT_BOLD
scale=1.75

[Tag h2]
foreground=#0184bc
weight=PANGO_WEIGHT_BOLD
scale=1.52

[Tag h3]
foreground=#0184bc
style=PANGO_STYLE_ITALIC
weight=PANGO_WEIGHT_BOLD
scale=1.32

[Tag h4]
foreground=#0184bc
weight=PANGO_WEIGHT_BOLD
scale=1.15

[Tag h5]
foreground=#0184bc
weight=PANGO_WEIGHT_BOLD

[Tag h6]
foreground=#0184bc

[Tag checked-checkbox]

[Tag xchecked-checkbox]

[Tag migrated-checkbox]

